  CREATE SEQUENCE "HACH2PROGRESS"."SEQ_PUNTO_INTERES" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 MINVALUE 1 CACHE 20;

  CREATE TABLE "HACH2PROGRESS"."PUNTO_INTERES" 
   (	"ID_PUNTO_INTERES" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"LATITUD" VARCHAR2(20 BYTE), 
	"LONGITUD" VARCHAR2(20 BYTE), 
	"ID_TIPO_PUNTO_INTERES" VARCHAR2(20 BYTE), 
	"CIUDAD" VARCHAR2(20 BYTE), 
	"COMUNIDAD_AUTONOMA" VARCHAR2(20 BYTE), 
	"URL" VARCHAR2(1000 BYTE), 
	"IMAGEN" BLOB, 
	"FECHA_CREACION" TIMESTAMP DEFAULT sysdate NOT NULL,
	"FECHA_MODIFICACION" TIMESTAMP,
	"FECHA_BAJA" TIMESTAMP, 
	 CONSTRAINT "PUNTOS_INTERES_PK" PRIMARY KEY ("ID_PUNTO_INTERES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  
  CREATE TABLE TIPO_PUNTO_INTERES 
(
  ID_TIPO_PUNTO_INTERES VARCHAR2(20) NOT NULL 
, NOMBRE VARCHAR2(20) 
, DESCRIPCION VARCHAR2(500) 
, CONSTRAINT TIPO_PUNTO_INTERES_PK PRIMARY KEY 
  (
    ID_TIPO_PUNTO_INTERES 
  )
  ENABLE 
);

  
